### ISSUE TITLE
update shader abstraction layer to use glsl->glsl compiler

### ISSUE THREAD

**Issue by Aeva** [Aeva/m.grl#174]
This is a follow-up to #149, which is responsible for building the essential compiler, and then integrating it into existing APIs.

This ticket will cover the following:
 - ~~use compiler for discovering available bindings, type signatures, etc, rather than webgl's introspection.~~on second thought, works fine as it is now
 - [x] special bindings, where a string is expected instead of a number, but a number is uploaded (#94 does this now)
 - [ ] shader composition; build a shader program with multiple sources (~~might happen as part of #149~~)
 - [x] ~~subshaders - compile multiple shaders into one; controlled by a 'special binding'~~ (I think this is just what #94 does now, I don't remember what I originally meant by this though)
