### ISSUE TITLE
Exporting lights and camera

### ISSUE THREAD

**Issue by Aeva** [Aeva/m.grl#51]
Add the following constructors to M.GRL
- [x] add CameraNode
- [x] ~~add DynamicCamera~~ CameraNode covers this functionality
- [x] change how the graph determines the active camera
- [x] a callback for when a camera is no longer active
- [x] document CameraNode
- [x] remove PerspectiveCamera
- [x] ~~add SunLight~~ added in #225
- [x] ~~add SpotLight~~ added in #164
- [x] ~~add PointLight~~ added in #225

The Blender exporter should also export all of these objects, even if they don't immediately do anything in M.GRL. 
- [ ] export blender cameras as CameraNode
- [ ] export 'sun' light sources as SunLight
- [ ] export spot light sources as SpotLight
- [ ] export point lights as PointLight

This may also engender exporting empties in some way, which is also a thing issue #48 needs.
- [ ] export JTA objects with no rendering information associated with them

I've made some speculative revisions to the JTA format document https://github.com/Aeva/m.grl/wiki/JTA-with-keyframes-specification which covers some of the features described in this ticket.

**better camera nodes**:
Smart cameras that can do things like follow around an object with some specific rules.  Cameras that can be exported from blender scenes that don't specifically focus on objects but can be animated in blender.  And maybe some other types.

**camera projection**:
There should be a means of doing 2D projection (x and y are screen coordinates, z is for sorting), as well as isometric projection, and some things inbetween.  It would be nice to have a projection mode where I can mix 3D assets with 2D LPC sprites and conform to the LPC style guide.  This might belong in some kind of m.cameras.js instead of the prefabs file.

**light sources**:
As far as the prefab system cares, these objects are just empties with metadata.  This would allow point lights, spot lights, and directional light to be animated and exported from blender.  The metadata from these "lights" might be used to in an actual lighting system somewhere, though one could just as well parent a translucent billboard sprite to one of these if that gave the effect they liked (or for debugging).  The specifics of the metadata may be the scope of another issue; and it may just be the case that this belongs in m.graph.js instead of m.prefab.js.  Or maybe some kind of m.lights.js

**Comment by Aeva** [comment]
Issue #225 added the remaining light types.
